### ISSUE TITLE
Proposal: Move Keptn Lifecycle Controller into main Keptn org

### ISSUE THREAD

**Issue by thisthat** [keptn/community#176]
The [Keptn Lifecycle Controller](https://github.com/keptn-sandbox/lifecycle-controller) has been developed into the sandbox organisation because it started as prototype. Given the recent development, the project has matured and can be used for real work deployments. Hence, I propose to promote the Lifecycle controller to be part of the main Keptn org to foster its deployment and make it ready for enterprise users.

https://github.com/keptn/community/issues/176#tasklist-block-bb1c31ec-e7bb-4697-b3e9-c32703f6cccb

**Comment by thschue** [comment]
I support

**Comment by grabnerandi** [comment]
I support this as well as I think this really solves a problem when it comes to managing the lifecycle of deployments on k8s

**Comment by oleg-nenashev** [comment]
I support, especially due to the process&outreach issues. A few reasons why:

* Keptn agenda at Kubecon is heavy, and it would be nice to have it in the main repository from the traffic perspective
* There is no way to move projects between orgs in GitHub Projects 2.0. When we move the project later, it will break roadmap and backlog which we promote in external materials
* Same for resources and for online documentation I'd like to publish

I recommend keeping the incubating status in READMEs though

**Comment by bradmccoydev** [comment]
I support this and am looking forward to the success of this project.

**Comment by oleg-nenashev** [comment]
Based on the feedback here and on Slack, I'll go ahead 🚀

**Comment by oleg-nenashev** [comment]
The repository was moved by now. See https://github.com/keptn/lifecycle-controller/issues/202 for the full steps
